#si estas desarrollando un ms debes dejarlo en localhost
#si estas ejecutando el contenedor del ms colocar el nombre del contenedor y su misma red

server {
    listen 80;

    location /api/auth/ {
        proxy_pass http://ms_auth:3000;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location = /api/teachers/me/dashboard {
        proxy_pass http://ms_auth:3000;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    #MS ASISTENCIA

    location /api/anotaciones {
        proxy_pass http://ms_asistencia:3001;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location /api/asistencia {
        proxy_pass http://ms_asistencia:3001;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location = /api/docentes/cursos {
        proxy_pass http://ms_asistencia:3001;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location ~ ^/api/cursos/[^/]+/alumnos$ {
        proxy_pass http://ms_asistencia:3001;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    # MS COMUNICACIONES

    location /api/mensajes {
        proxy_pass http://ms_comunicaciones:3002;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    # MS GESTION

    location /api/academico {
        proxy_pass http://ms_gestion:8080;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location /api/docentes {
        proxy_pass http://ms_gestion:8080;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location /api/estudiantes {
        proxy_pass http://ms_gestion:8080;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location /api/evaluaciones {
        proxy_pass http://ms_gestion:8080;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location /api/notas {
        proxy_pass http://ms_gestion:8080;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }

    location /api/usuarios {
        proxy_pass http://ms_gestion:8080;
        include /etc/nginx/conf.d/proxy-headers.conf;
    }
}
